name: 'Labeler'
description: 'Automatically label new pull requests based on the paths of files being changed'
author: 'srz-zumix'
inputs:
  repo-token:
    description: 'The GitHub token used to manage labels'
    required: false
    default: ${{ github.token }}
  configuration-path:
    description: 'The path for the label configurations'
    default: '.github/labeler.yml'
    required: false
  sync-labels:
    description: 'Whether or not to remove labels when matching files are reverted'
    default: false
    required: false
  dot:
    description: 'This is a no side effect option for compatibility only'
    default: true
    required: false
  pr-number:
    description: 'The pull request number(s)'
    required: false

outputs:
  new-labels:
    description: 'A comma-separated list of all new labels'
  all-labels:
    description: 'A comma-separated list of all labels that the PR contains'

runs:
  using: 'composite'
  steps:
    - uses: aquaproj/aqua-installer@d1fe50798dbadd4eb5b98957290ca175f6b4870f # v4.0.2
      with:
        aqua_version: 2.53.9
        policy_allow: true
        working_directory: ${{ github.actions_path }}
    - name: Labeler
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.repo-token }}
      run: |
        gh-label-kit labeler \
          --config ${{ inputs.configuration-path }} \
          ${{ inputs.sync-labels && '--sync' || '' }} \
          ${{ inputs.pr-number }}

branding:
  icon: 'terminal'
  color: 'black'
