name: 'gh-label-kit Labeler Action'
description: 'Automatically label new pull requests based on the paths of files being changed'
author: 'srz-zumix'
inputs:
  repo-token:
    description: 'The GitHub token used to manage labels'
    default: ''
    required: false
  configuration-path:
    description: 'The path for the label configurations'
    default: '.github/labeler.yml'
    required: false
  sync-labels:
    description: 'Whether or not to remove labels when matching files are reverted'
    default: false
    type: boolean
    required: false
  dot:
    description: 'This is a no side effect option for compatibility only'
    default: true
    type: boolean
    required: false
  pr-number:
    description: 'The pull request number(s)'
    default: ${{ github.event.number }}
    required: false
  review-request:
    description: |
      Control review request behavior:
        none (no requests),
        addto (request on new labels),
        ready_for_review (request on new labels when PR is ready for review, require ready_for_review activity),
        always_reviewable (request on all matched labels when PR is reviewable),
        always (request on all matched labels)
    default: 'addto'
    type: string
    required: false

outputs:
  new-labels:
    description: 'A comma-separated list of all new labels'
    value: ${{ steps.labeler.outputs.new-labels }}
  all-labels:
    description: 'A comma-separated list of all labels that the PR contains'
    value: ${{ steps.labeler.outputs.all-labels }}

runs:
  using: 'composite'
  steps:
    - uses: aquaproj/aqua-installer@ea518c135a02fc11ff8024364510c181a5c6b342 # v4.0.3
      with:
        aqua_version: v2.53.9
        # policy_allow: aqua-policy.yaml
        working_directory: ${{ github.action_path }}
    - name: gh-labeler-kit path
      id: gh-labeler-kit
      shell: bash
      env:
        GH_HOST: github.com
        GH_TOKEN: ""
        GH_ENTERPRISE_TOKEN: ""
        AQUA_POLICY_CONFIG: aqua-policy.yaml
      run: |
        gh-label-kit --version
        echo "path=$(aqua which gh-label-kit)" >> "${GITHUB_OUTPUT}"
      working-directory: ${{ github.action_path }}
    - name: Labeler
      id: labeler
      shell: bash
      env:
        INPUTS_GITHUB_TOKEN: ${{ inputs.repo-token }}
        INPUTS_CONFIGURATION_PATH: ${{ inputs.configuration-path }}
        INPUTS_PR_NUMBER: ${{ inputs.pr-number }}
        INPUTS_SYNC_LABELS: ${{ inputs.sync-labels }}
        INPUTS_REVIEW_REQUEST: ${{ inputs.review-request }}
        GH_LABELER_KIT: ${{ steps.gh-labeler-kit.outputs.path }}
      run: |
        export GH_TOKEN="${INPUTS_GITHUB_TOKEN:-${GH_TOKEN:-${{ github.token }}}}"
        export GH_ENTERPRISE_TOKEN="${INPUTS_GITHUB_TOKEN:-${GH_ENTERPRISE_TOKEN:-${{ github.token }}}}"

        LABEL_KIT_OPTIONS=()
        if [ "${INPUTS_SYNC_LABELS}" = "true" ]; then
          LABEL_KIT_OPTIONS+=(--sync)
        fi
        if [ -n "${INPUTS_REVIEW_REQUEST}" ]; then
          LABEL_KIT_OPTIONS+=(--review-request "${INPUTS_REVIEW_REQUEST}")
        fi
        set -x
        "${GH_LABELER_KIT}" labeler \
          --config ${INPUTS_CONFIGURATION_PATH} \
          "${LABEL_KIT_OPTIONS[@]}" \
          ${INPUTS_PR_NUMBER}

branding:
  icon: 'bookmark'
  color: 'gray-dark'
