name: 'gh-label-kit Labeler Action'
description: 'Automatically label new pull requests based on the paths of files being changed'
author: 'srz-zumix'
inputs:
  repo-token:
    description: 'The GitHub token used to manage labels'
    default: ${{ github.token }}
    required: false
  configuration-path:
    description: 'The path for the label configurations'
    default: '.github/labeler.yml'
    required: false
  sync-labels:
    description: 'Whether or not to remove labels when matching files are reverted'
    default: false
    type: boolean
    required: false
  dot:
    description: 'This is a no side effect option for compatibility only'
    default: true
    type: boolean
    required: false
  pr-number:
    description: 'The pull request number(s)'
    default: ${{ github.event.number }}
    required: false

outputs:
  new-labels:
    description: 'A comma-separated list of all new labels'
    value: ${{ steps.labeler.outputs.new-labels }}
  all-labels:
    description: 'A comma-separated list of all labels that the PR contains'
    value: ${{ steps.labeler.outputs.all-labels }}

runs:
  using: 'composite'
  steps:
    - uses: aquaproj/aqua-installer@d1fe50798dbadd4eb5b98957290ca175f6b4870f # v4.0.2
      with:
        aqua_version: v2.53.9
        policy_allow: true
        working_directory: ${{ github.action_path }}
    - name: gh-labeler-kit path
      id: gh-labeler-kit
      shell: bash
      run: |
        gh-label-kit --version
        echo "path=$(aqua which gh-label-kit)" >> "${GITHUB_OUTPUT}"
      working-directory: ${{ github.action_path }}
    - name: Labeler
      id: labeler
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.repo-token }}
        INPUTS_CONFIGURATION_PATH: ${{ inputs.configuration-path }}
        INPUTS_PR_NUMBER: ${{ inputs.pr-number }}
        INPUTS_SYNC_LABELS: ${{ inputs.sync-labels }}
        GH_LABELER_KIT: ${{ steps.gh-labeler-kit.outputs.path }}
      run: |
        LABEL_KIT_OPTIONS=()
        if [ "${INPUTS_SYNC_LABELS}" = "true" ]; then
          LABEL_KIT_OPTIONS+=(--sync)
        fi
        set -x
        "${GH_LABELER_KIT}" labeler \
          --config ${INPUTS_CONFIGURATION_PATH} \
          "${LABEL_KIT_OPTIONS[@]}" \
          ${INPUTS_PR_NUMBER}

branding:
  icon: 'bookmark'
  color: 'gray-dark'
