name: 'gh-label-kit Labeler Action'
description: 'Automatically label new pull requests based on the paths of files being changed'
author: 'srz-zumix'
inputs:
  repo-token:
    description: 'The GitHub token used to manage labels'
    default: ''
    required: false
  configuration-path:
    description: 'The path for the label configurations'
    default: '.github/labeler.yml'
    required: false
  sync-labels:
    description: 'Whether or not to remove labels when matching files are reverted'
    default: false
    type: boolean
    required: false
  dot:
    description: 'Whether or not to auto-include paths starting with dot (e.g. `.github`)'
    default: true
    type: boolean
    required: false
  pr-number:
    description: 'The pull request number(s)'
    default: ${{ github.event.number }}
    required: false
  review-request:
    description: |
      Control review request behavior:
        none (no requests),
        addto (request on new labels),
        ready_for_review (request on new labels when PR is ready for review, require ready_for_review activity),
        always_reviewable (request on all matched labels when PR is reviewable),
        always (request on all matched labels)
    default: 'addto'
    type: string
    required: false
  strict-config:
    description: 'Whether or not to fail if the configuration file is invalid'
    default: false
    type: boolean
    required: false
  cache:
    description: 'Whether or not to use aqua install cache'
    default: true
    type: boolean
    required: false

outputs:
  new-labels:
    description: 'A comma-separated list of all new labels'
    value: ${{ steps.labeler.outputs.new-labels }}
  all-labels:
    description: 'A comma-separated list of all labels that the PR contains'
    value: ${{ steps.labeler.outputs.all-labels }}
  cache-hit:
    description: 'Whether or not the cache was hit'
    value: ${{ steps.aqua-cache.outputs.cache-hit }}

runs:
  using: 'composite'
  steps:
    - uses: srz-zumix/aqua-installer-cache@b0c06a58d8c2a2c9a7381c7e722675d1f4b68a5c # v0.2.0
      id: aqua-cache
      with:
        working-directory: ${{ github.action_path }}
        config-file: aqua.yaml
      if: inputs.cache == 'true'
    - uses: aquaproj/aqua-installer@11dd79b4e498d471a9385aa9fb7f62bb5f52a73c # v4.0.4
      with:
        aqua_version: v2.55.3
        # policy_allow: aqua-policy.yaml
        working_directory: ${{ github.action_path }}
    - name: gh-labeler-kit path
      id: gh-labeler-kit
      shell: bash
      env:
        GH_HOST: github.com
        GH_ENTERPRISE_TOKEN: ""
        AQUA_POLICY_CONFIG: aqua-policy.yaml
      run: |
        export GH_TOKEN="${AQUA_GITHUB_TOKEN:-}"
        gh-label-kit --version
        echo "path=$(aqua which gh-label-kit)" >> "${GITHUB_OUTPUT}"
      working-directory: ${{ github.action_path }}
    - name: Labeler
      id: labeler
      shell: bash
      env:
        INPUTS_GITHUB_TOKEN: ${{ inputs.repo-token }}
        INPUTS_CONFIGURATION_PATH: ${{ inputs.configuration-path }}
        INPUTS_PR_NUMBER: ${{ inputs.pr-number }}
        INPUTS_SYNC_LABELS: ${{ inputs.sync-labels }}
        INPUTS_REVIEW_REQUEST: ${{ inputs.review-request }}
        INPUTS_DOT: ${{ inputs.dot }}
        INPUTS_STRICT_CONFIG: ${{ inputs.strict-config }}
        GH_LABELER_KIT: ${{ steps.gh-labeler-kit.outputs.path }}
      run: |
        export GH_TOKEN="${INPUTS_GITHUB_TOKEN:-${GH_TOKEN:-${{ github.token }}}}"
        export GH_ENTERPRISE_TOKEN="${INPUTS_GITHUB_TOKEN:-${GH_ENTERPRISE_TOKEN:-${{ github.token }}}}"

        LABEL_KIT_OPTIONS=()
        if [ "${INPUTS_SYNC_LABELS}" = "true" ]; then
          LABEL_KIT_OPTIONS+=(--sync)
        fi
        if [ -n "${INPUTS_REVIEW_REQUEST}" ]; then
          LABEL_KIT_OPTIONS+=(--review-request "${INPUTS_REVIEW_REQUEST}")
        fi
        if [ "${INPUTS_DOT}" = "false" ]; then
          LABEL_KIT_OPTIONS+=(--no-hidden)
        fi
        if [ "${INPUTS_STRICT_CONFIG}" = "true" ]; then
          LABEL_KIT_OPTIONS+=(--strict)
        fi
        set -x
        "${GH_LABELER_KIT}" labeler \
          --config ${INPUTS_CONFIGURATION_PATH} \
          "${LABEL_KIT_OPTIONS[@]}" \
          ${INPUTS_PR_NUMBER}

branding:
  icon: 'bookmark'
  color: 'gray-dark'
