name: Self Test
on:
  pull_request:
  workflow_dispatch:
    inputs:
      pr-number:
        description: 'The pull request number(s)'
        required: true

jobs:
  test:
    permissions:
      contents: read
      pull-requests: write
      issues: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          path: labeler
          persist-credentials: false
      - name: labeler
        id: labeler
        uses: ./labeler
        with:
          pr-number: ${{ github.event.inputs.pr-number || github.event.number }}
      - name: Test
        shell: bash
        env:
          ALL_LABELS: ${{ steps.labeler.outputs.all-labels }}
        run: |
          test -n "${ALL_LABELS}"
