name: Self Test
on:
  pull_request:

jobs:
  test:
    permissions:
      contents: read
      pull-requests: write
      issues: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: labeler
        id: labeler
        uses: ./
