name: Self Test
on:
  pull_request:

jobs:
  test:
    permissions:
      contents: read
      pull-requests: write
      issues: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          path: labeler
      - name: labeler
        id: labeler
        uses: ./labeler
      - name: Test
        shell: bash
        run: |
          test -n "${{ steps.labeler.outputs.all-labels }}"
